# Generated by Django 5.2.1 on 2025-05-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetup_bot", "0003_event_rename_telegram_username_customuser_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("guest", "guest"),
                    ("speaker", "speaker"),
                    ("organizer", "organizer"),
                ],
                default="guest",
                help_text="User's role in the system",
                max_length=10,
                null=True,
            ),
        ),
    ]
